name: gptva
description: "Voice Assistant that uses Chatgpt"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3

  # sign in services
  google_fonts: ^4.0.3

  # state managment
  provider: ^6.1.1

  # markdown

  flutter_markdown: ^0.6.18+2
  markdown: ^7.1.1

  # local data
  shared_preferences: ^2.2.2

  # helpers & tools
  # cached_network_image: ^3.3.0
  flutter_highlighter: ^0.1.1
  http: ^1.1.2
  url_launcher: ^6.2.2
  # photo_view: ^0.14.0
  # beautiful_soup_dart: ^0.3.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

